### ISSUE TITLE
尝试使用DataGrip导入csv文件报错

### ISSUE THREAD

**Issue by longmenzhitong** [skywind3000/ECDICT#108]
报错日志：
<img width="697" alt="image" src="https://github.com/skywind3000/ECDICT/assets/101724143/f4bb1ad1-4b31-4323-9f5a-2611e819be73">
导入选项：
![image](https://github.com/skywind3000/ECDICT/assets/101724143/0b178647-5ab3-4562-8af7-2c82958107fb)
HELP!!!

**Comment by skywind3000** [comment]
你直接用 release 里面的 sqlite 数据库导入吧。

**Comment by longmenzhitong** [comment]
> 你直接用 release 里面的 sqlite 数据库导入吧。

好的，我尝试一下，谢谢！
