### ISSUE TITLE
我下载表格打开发现是乱码，是为什么呢？

### ISSUE THREAD

**Issue by jsonhet** [skywind3000/ECDICT#109]
wps打开是这样，是为什么呢？
![QQ图片20230724101755](https://github.com/skywind3000/ECDICT/assets/31009976/d7af51d5-ade0-4c06-9b95-d9cbf5342ff6)

**Comment by skywind3000** [comment]
不知道，没试过 wps，直接到 release 里面下载 sqlite 数据库呗。

**Comment by jsonhet** [comment]
> 不知道，没试过 wps，直接到 release 里面下载 sqlite 数据库呗。
选文件导入后好了。
感谢，我还想着把表格数据写入数据库呢。
