### ISSUE TITLE
有些时态变换模式没有描述：f / b / z

### ISSUE THREAD

**Issue by jadyyang** [skywind3000/ECDICT#113]
包含这三种变化的不太多，不过感觉像：
f: 复数（是的话，跟 s 有什么差别？）
b / z： 比较级 和 最高级（跟 r / t 有什么差别？）

比如几个例子：
replete： s:repletes/b:more replete/z:most replete/f:repletes
low：       s:lows/b:lower/d:lowed/f:lows/i:lowing/p:lowed/3:lows/z:lowest/r:lower/t:lowest

还请知道的同学指正下

**Comment by skywind3000** [comment]
有些老数据没删除吧，以我文档表格为主。

**Comment by jadyyang** [comment]
thanks
