### ISSUE TITLE
在哪种词典格式里查询单词后返回释义结果时间最短？

### ISSUE THREAD

**Issue by redstoneleo** [skywind3000/ECDICT#12]
目前我知道这几个词典格式：mdx、eudic、stardict、CSV、SQLite、MySQL
想知道在哪种词典格式里从查询单词到返回释义结果的时间最短？

目前从[这里](https://github.com/skywind3000/ECDICT#%E8%AF%8D%E5%85%B8%E4%BD%BF%E7%94%A8)了解到的是

> 本地使用 csv很痛苦，文件大了打开速度很慢。所以自己使用时，一般都是转换成本地的 SQLite 数据库，这样快速很多，基本没有等待，查单词也很迅速。

但是并没有提及其他几个格式的情况，请大家发表下看法

**Comment by skywind3000** [comment]
肯定是 sqlite 啊

**Comment by redstoneleo** [comment]
@skywind3000 大佬可以解释下原因吗？

**Comment by redstoneleo** [comment]
一番摸索之后，发现同样内容的词典转成mdx后，体积比sqlite 的小，另外mdx在流行度和资源数量上都比较多，所以我最终选定mdx
