### ISSUE TITLE
编程接口使用的问题

### ISSUE THREAD

**Issue by redstoneleo** [skywind3000/ECDICT#13]
我这么用
```
import stardict
dict = stardict.StarDict(r'C:\Users\i\Downloads\简明增强-css\concise-enhanced.mdx.db', verbose = True)
result = dict.query('hi')
print(result)

```
为什么没有查询结果啊？

**Comment by skywind3000** [comment]
你这db是哪里来的？

**Comment by redstoneleo** [comment]
我试过
https://github.com/mmjang/mdict-query    （把本项目的mdx转成db文件）
和
https://github.com/ilius/pyglossary             （把本项目的csv转成sqlite文件）
按照上面的方法访问转出的文件均无法出翻译结果

**Comment by skywind3000** [comment]
请用 startdict.convert_dict("XXX.csv", "XXX.db") 转换

**Comment by redstoneleo** [comment]
我已经试过了，还是不行，具体情况看这里https://github.com/skywind3000/ECDICT/issues/10#issuecomment-361066915
我找另外一台64位的机器转也还是同样的问题。

大哥能否转一份出来网盘分享下，谢谢！

**Comment by redstoneleo** [comment]
是我参数位置搞错的问题
https://github.com/skywind3000/ECDICT/issues/10#issuecomment-361539277
