### ISSUE TITLE
DictMySQL中的几个BUG

### ISSUE THREAD

**Issue by GraphicSound** [skywind3000/ECDICT#24]
1. 没有commit函数，convert_dict会报错

2. delete_all中：
        self.__cursor.execute(sql1)
	self.__conn.commit()
需要改成
        with self.__conn as c:
	       c.execute(sql1)
不知道为什么

3. 写入mysql数据库的时候会有几种warning：
Warning: Incorrect string value
Warning: Data truncated for column

**Comment by skywind3000** [comment]
多谢。

**Comment by skywind3000** [comment]
因为我百分之九十的时间是在用 sqlite, csv 两个版本。
