### ISSUE TITLE
多音词的音标不支持多音标

### ISSUE THREAD

**Issue by zhangkaizhao** [skywind3000/ECDICT#27]
非常感谢制作这个非常棒的词典！
只是目前多音词的音标不支持多音标，是否考虑支持呢？
比如单词 wind 在表示不同词意时候有 `[wind]` 和 `[waind]` 两个发音；而单词 record 在词性不同时候有 `['rekɔ:d]` 和 `[ri'kɔ:d]` 两个发音，等等。

**Comment by skywind3000** [comment]
工作量太大，要支持多音标。
