### ISSUE TITLE
goldendict 加载问题

### ISSUE THREAD

**Issue by TheKiteRunning** [skywind3000/ECDICT#3]
感觉没有加载完全，如图。

![image](https://cloud.githubusercontent.com/assets/24802332/25564413/6b34c4ea-2de5-11e7-877a-7c715dfd8eca.png)

goldendict版本
![image](https://cloud.githubusercontent.com/assets/24802332/25564421/91ceeafe-2de5-11e7-9e6e-b7d3e11e0cb6.png)

**Comment by skywind3000** [comment]
什么叫做没有加载完全？从哪里看出来没加载完全啊？

**Comment by TheKiteRunning** [comment]
第一张图的左下角又一个紫色矩形框住的提示，不过后来这个提示消失了感谢。

**Comment by skywind3000** [comment]
那是在做全文索引，不影响使用，全文索引完成后，就可以全文搜索了，这是 GoldenDict 的一个比较好的功能，可以让你在若干字典的例句中搜索某个单词和词组的所有用法。

**Comment by skywind3000** [comment]
话说，你可以把你的 GoldenDict 风格改为“现代"
