### ISSUE TITLE
edict.csv中只有77万行，300万的csv在哪里可以找到呢

### ISSUE THREAD

**Issue by jotline** [skywind3000/ECDICT#30]

**Comment by jotline** [comment]
已解决，在7z压缩包里。

**Comment by jotline** [comment]
-

**Comment by skywind3000** [comment]
https://github.com/skywind3000/ECDICT-ultimate/releases
看这里，425万词库的升级版，这个升级版有多强？

看下文介绍：
https://zhuanlan.zhihu.com/p/31493883
