### ISSUE TITLE
查找包含“特定单词”的词组

### ISSUE THREAD

**Issue by urna** [skywind3000/ECDICT#38]
目前的match函数只能查询以特定单词开始的条目，be good at 用be可以查询到，可是用good查不到，希望实现查找包含“特定单词”的词组

**Comment by urna** [comment]
sqlite的word列已经有索引，不知道用like查询效率问题大不大

**Comment by urna** [comment]
也许用sqlite 的full text search实现更合理，没用过，不知道性能如何，研究一下

**Comment by skywind3000** [comment]
对于全文搜索，sqlite 的 like ，其实就是 for 循环每个key，没什么优化的，你要全文搜索的话，可以自己建索引。

**Comment by skywind3000** [comment]
sqlite 全文搜索我没有使用过。python 自带的 sqlite 全文搜索可以用么？

**Comment by skywind3000** [comment]
不行的话，自建索引吧：
https://pypi.org/project/Whoosh/

**Comment by urna** [comment]
> 不行的话，自建索引吧：
> https://pypi.org/project/Whoosh/

试一试，做index时候，把单个的词排除掉，只index词组，应该数据量会少很多应该

**Comment by skywind3000** [comment]
分词的话就简单很多了。

**Comment by skywind3000** [comment]
如果你求一下 lemma 再搜索，效果可能更好。

**Comment by urna** [comment]
> 如果你求一下 lemma 再搜索，效果可能更好。

是这样想的，index和搜索之前，都lemma。我现在用elastic search，它的lemma是基于规则的，和你的dict based不一致。index和search的lemma算法应该一致，现在想都采用dict based，如果用es，还的做个插件扩展，麻烦，我试试Whoosh，最好都搞成python的一致了

**Comment by urna** [comment]
> 如果你求一下 lemma 再搜索，效果可能更好。

index dict词组的时候，应该不用lemma吧？ 我看了下，基本都是base form。感觉只是搜索时候lemma就行

**Comment by urna** [comment]
[index_dict.py.txt](https://github.com/skywind3000/ECDICT/files/2921637/index_dict.py.txt)

well done! it works and the script to export phrase from edict sqlite db to whoosh index is attached

**Comment by skywind3000** [comment]
牛了。
