### ISSUE TITLE
请问能不能生成mac自带字典的格式

### ISSUE THREAD

**Issue by AlickH** [skywind3000/ECDICT#4]
如果能的话就太好了

**Comment by skywind3000** [comment]
我有空看一下 Kindle 和  mac 词典的做法，应该问题不大。

**Comment by SIDmao** [comment]
非常感谢

**Comment by dongyuwei** [comment]
集成到Mac Dictionary.app 也不难。可以参考我的 拼音-英语词典
 https://github.com/dongyuwei/Pinyin2English
先下载apple的Dictionary Development Kit（我用的是Additional_Tools_for_Xcode_9.dmg中附带的），里面有project_templates及文档说明。基本上就是根据词库生成一个巨大的xml（在其中声明单词及其发音、释义及索引等），样式用css定义，然后用Dictionary Development Kit编译成可以添加到Dictionary.app的词典。

**Comment by dongyuwei** [comment]
我用这个项目最新的ecdict.csv词库生成了一份可以集成到Mac Dictionary.app中的词典：https://github.com/dongyuwei/ECDICT/tree/master/mac_dictionary ，但是文件太大了，无法上传。编译时间也耗时甚久。感兴趣的朋友可以clone源码自行编译。

**Comment by skywind3000** [comment]
多谢，你能不能压缩以后放到百度云盘里面给大家共享一下啊？

**Comment by dongyuwei** [comment]
这份是昨晚编译的，不是最新版，但基本可用：https://pan.baidu.com/s/1kXkoFSN

**Comment by dongyuwei** [comment]
下载后解压到 ~/Library/Dictionaries/ 目录， 打开 Dictionary.app，点击 `Preferences...`，启用ecdict。
![image](https://user-images.githubusercontent.com/112451/35190066-ee9714ee-fe93-11e7-9ead-4612d2233817.png)

**Comment by dongyuwei** [comment]
@skywind3000 如果需要，我可以提一个pull-request，把功能合并到这个项目中。

**Comment by dongyuwei** [comment]
demo：
![image](https://user-images.githubusercontent.com/112451/35190118-f6c88534-fe94-11e7-88af-fc27c7a0fc8f.png)

![image](https://user-images.githubusercontent.com/112451/35190123-2a6dd2f4-fe95-11e7-982c-a81b2613764f.png)

**Comment by ichswarox** [comment]
11.12.6 提供的dictionary文件无法在字典设置中找到

**Comment by dongyuwei** [comment]
> 11.12.6 提供的dictionary文件? 
重启 Dictionary.app 试试

**Comment by ichswarox** [comment]
@dongyuwei 没用的，下载一个越南语的dictionary文件，重启后可以看到，所以怀疑是.dictionary文件的问题。

**Comment by hffqyd** [comment]
@dongyuwei 你好！请问可以分享下你的编译macOS词典的方法吗？需要什么工具？转换ECDict这么多条目的词典大概需要多少时间呢？谢谢～

**Comment by dongyuwei** [comment]
@hffqyd 谢谢关注！
参考 https://github.com/dongyuwei/ECDICT/blob/master/mac_dictionary/README.md

**Comment by YunchengLiao** [comment]
https://github.com/ilius/pyglossary

参考这个项目，字典格式转换工具。

**Comment by the0demiurge** [comment]
楼上给的字典文件格式不太完善，我用python做了一下转码，基本完美，且可在设置界面中选择部分内容的隐藏与显示。
链接: https://pan.baidu.com/s/1I-Ac8G5agOf5wXMrBlG_fA 提取码: 8q3k

代码与编译指南在
https://github.com/the0demiurge/Python-Scripts/tree/master/src/MinorProjects/ECDICT

**Comment by skywind3000** [comment]
@the0demiurge 你能不能转码一下：

https://github.com/skywind3000/ECDICT-ultimate/ 

这里的库呢？这个是 430w 词条的《简明英汉必应版》

**Comment by the0demiurge** [comment]
链接: https://pan.baidu.com/s/1LTIrJn6eD4vPkn4oHnsffg  密码: uch2
改进了一下index的生成方式，并且可以选择隐藏姓名的释义

**Comment by skywind3000** [comment]
帅

**Comment by gaozhanting** [comment]
> 楼上给的字典文件格式不太完善，我用python做了一下转码，基本完美，且可在设置界面中选择部分内容的隐藏与显示。
> 链接: [pan.baidu.com/s/1I-Ac8G5agOf5wXMrBlG_fA](https://pan.baidu.com/s/1I-Ac8G5agOf5wXMrBlG_fA) 提取码: 8q3k
> 
> 代码与编译指南在
> [https://github.com/the0demiurge/Python-Scripts/tree/master/src/MinorProjects/ECDICT](https://github.com/the0demiurge/Python-Scripts/tree/master/src/MinorProjects/ECDICT?rgh-link-date=2020-03-16T12%3A06%3A14Z)

调用DCSCopyTextDefinition报错
Variable 'display-definition' has not been declared.

**Comment by the0demiurge** [comment]
有详细的traceback吗，很久没用过这个了，已经完全记不得你说的是什么了。另外，看变量名大概是苹果字典工具箱的问题

**Comment by gaozhanting** [comment]
这个API只有两个方法；很老；；traceback都是汇编代码。。
大概意思应该是xml没有提供display-definition这个key。。

**Comment by zfdang** [comment]
> > 楼上给的字典文件格式不太完善，我用python做了一下转码，基本完美，且可在设置界面中选择部分内容的隐藏与显示。
> > 链接: [pan.baidu.com/s/1I-Ac8G5agOf5wXMrBlG_fA](https://pan.baidu.com/s/1I-Ac8G5agOf5wXMrBlG_fA) 提取码: 8q3k
> > 代码与编译指南在
> > [https://github.com/the0demiurge/Python-Scripts/tree/master/src/MinorProjects/ECDICT](https://github.com/the0demiurge/Python-Scripts/tree/master/src/MinorProjects/ECDICT?rgh-link-date=2020-03-16T12%3A06%3A14Z)
> 
> 调用DCSCopyTextDefinition报错 Variable 'display-definition' has not been declared.

这个版本貌似没法正常使用啊，必应版没法使用，增强版倒是正常的
