### ISSUE TITLE
cursor not closed in stardict.py

### ISSUE THREAD

**Issue by urna** [skywind3000/ECDICT#40]
In "stardict.py", cursors are not closed after using, not sure whether there will be memory leak issue.

But in sqlite3 c source code, the "close" function is not empty [pysqlite_cursor_close](https://github.com/python/cpython/blob/master/Modules/_sqlite/cursor.c):
(void)pysqlite_statement_reset(self->statement);
Py_CLEAR(self->statement);

However, I think it is better to close cursors ASAP, saving memory when running on cheaper cloud VMs.

**Comment by skywind3000** [comment]
Right now I have no time working on it. You can send me PR for this.

**Comment by urna** [comment]
i will study how PR  works

**Comment by urna** [comment]
had sent  PR for this
