### ISSUE TITLE
StartDict sqlite multi thread exception

### ISSUE THREAD

**Issue by urna** [skywind3000/ECDICT#41]
> sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in thread xxxx

StartDict sqlite class showes above exception with multi thread.
simply I just change "self.__conn = sqlite3.connect(self.__dbname, isolation_level = "IMMEDIATE",check_same_thread = False)", to add last parameter

for lookups/query, it works ok, but for writing, there may be issue.

**Comment by skywind3000** [comment]
You can create multiple StarDict sqlite classes specific to each thread.

**Comment by urna** [comment]
got it!
we should avoid using shared/global starDict object!
