### ISSUE TITLE
部分选词来源欠清楚

### ISSUE THREAD

**Issue by acgtyrant** [skywind3000/ECDICT#52]
比如所谓四六级考试大纲是否出自 2016 年的词表？http://cet.neea.edu.cn/html1/folder/16113/1588-1.htm

考研英语呢？

托福雅思好像没有官方词表，不知数据是哪里来的。

所谓宝即 GRE 红宝书，又是第几版呢？

**Comment by skywind3000** [comment]
记不得了。

**Comment by skywind3000** [comment]
你要做的这么精确的话，你可以自己考证一遍。

**Comment by skywind3000** [comment]
我记得我大体上还是找到过一些相对来讲可信度比较高的资料，包括中考高考教学大纲之类的。但是你真要说多精确，我不敢给你保证。
