### ISSUE TITLE
lemma.en.txt 的 32177 行有误

### ISSUE THREAD

**Issue by 1024th** [skywind3000/ECDICT#58]
lemma.en.txt 的 32177 行有误：

```
conjurer/15 -> conjurers,also,spelled
```

`conjurer`怎么会和`also,spelled`有关系呢？我猜源数据是像`conjurers(also spelled conjurors)`这样的，程序处理时发生了错误。

**Comment by skywind3000** [comment]
多谢，上亿条的语料库，偶尔也有几条错误，不是程序问题，就是语料库有错乱文本，但是占比很少。

**Comment by skywind3000** [comment]
已经修正。
