### ISSUE TITLE
water这条数据有问题 解析用逗号的时候

### ISSUE THREAD

**Issue by largefire** [skywind3000/ECDICT#61]
water,'wɒ:tә,"n. binary compound that occurs at room temperature as a clear colorless odorless tasteless liquid; freezes into ice below 0 degrees centigrade and boils above 100 degrees centigrade; widely used as a solvent\nn. once thought to be one of four elements composing the universe (Empedocles)\nn. a liquid necessary for the life of most animals and plants\nv. supply with water as with channels or ditches or streams","n. 水, 雨水, 海水, 水位, 水面, 流水\nvt. 给...浇水, 供以水, 注入水, 使湿\nvi. 流泪, 流口水, 加水\na. 水的, 水上的, 水生的, 含水的",v:2/n:98,5,1,zk gk ielts,236,226,s:waters/d:watered/i:watering/3:waters/p:watered,,

**Comment by skywind3000** [comment]
我的数据没有任何问题，用的python标准库里的csv模块输出的，excel也能正常打开。

你自己不了解csv格式，你的程序不完善，无法解析双引号，还来这开 issue

shame

**Comment by largefire** [comment]
CSV全称是：Comma Separated Values 或者 Character Separated Values。

尽管第一种说法更常见，但我觉得还是第二种说法更确切一些，因为你可以使用其它字符做分隔符。

使用逗号做分隔符的CSV文件有一个好处：你可以直接用Excel打开。如果使用其它分隔符，比如“|”，你必须告诉Excel该文件使用“|”作分隔符，Excel才能把它导入进来。

前几天，project manager告诉我：我们有许多CSV文件，都是使用“|”做分隔符，用Excel打开的时候比较麻烦，用户想在Excel中直接打开。这样就需要使用“,”做分隔符。但是文件中有些字段含有逗号，必须对这些逗号特殊处理，才能保证CSV文件在Excel中正确打开。他还给了我一个算法：

如果字段中有逗号（,），该字段使用双引号（”）括起来；

如果该字段中有双引号，该双引号前要再加一个双引号，然后把该字段使用双引号括起来。
————————————————
版权声明：本文为CSDN博主「十一路客」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/xyr05288/article/details/53696464
