### ISSUE TITLE
stardict.csv 里面csv的分隔符 解析出来的数据 本来是打算用逗号,分开的 但是在transaction等字段中还是包含很多逗号

### ISSUE THREAD

**Issue by largefire** [skywind3000/ECDICT#62]
stardict.csv 里面的解析出来的数据 本来是打算用逗号,分开的 但是在transaction等字段中还是包含很多逗号 这样导致条件解析不过来 。建议统一用一个字符 或者把不对的字符改掉。特别是csv的分隔符

**Comment by skywind3000** [comment]
csv格式碰到字段里有逗号可以用双引号引起来，这是标准，excel识别的方式，你需要的是完善下你自己的解析代码，别乱建议些错误格式。

**Comment by largefire** [comment]
哦 好的 我明白了 谢谢
