### ISSUE TITLE
要如何将数据导入到MySql中去？

### ISSUE THREAD

**Issue by li-car-fei** [skywind3000/ECDICT#66]

**Comment by skywind3000** [comment]
自己看一下 stardict.py 中 csv/sqlite/mysql 的接口便知。

**Comment by cupen** [comment]
有了 csv , 剩下的事很容易的.  
需要的话给我买两杯咖啡, 偶阔以帮你搞定哟. :smiley:

**Comment by li-car-fei** [comment]
> 自己看一下 stardict.py 中 csv/sqlite/mysql 的接口便知。

stardict.py 里只提供了转sqlite的接口吧？

**Comment by skywind3000** [comment]
照葫芦画瓢不会么？那么大一个 DictMySQL 的类在那里没看到？？
