### ISSUE TITLE
csv导出到mysql的问题

### ISSUE THREAD

**Issue by jiawei666** [skywind3000/ECDICT#67]
### 提几个小建议
1. `python3`已经不支持安装`mysql-python`，因此不完全兼容`python3`
2. 建议生成`requirement`文件
3. 建议在`readme.md`增加简单的使用文档，或者在`startdict.py`最后增加几个test方法案例

**Comment by skywind3000** [comment]
第一，mysql-python 有 python 3  版本，ubuntu/debian 下面直接

    apt-get install python3-mysql

就有了，不想 apt-get 安装的话，你可以用：

- https://pypi.org/project/PyMySQL/ 
- https://pypi.python.org/pypi/mysql-connector-python

两个都可以，看你喜欢，完全代替 MySQLdb 的，

**Comment by jiawei666** [comment]
> 第一，mysql-python 有 python 3 版本，ubuntu/debian 下面直接
> 
> ```
> apt-get install python3-mysql
> ```
> 
> 就有了，不想 apt-get 安装的话，你可以用：
> 
> * https://pypi.org/project/PyMySQL/
> * https://pypi.python.org/pypi/mysql-connector-python
> 
> 两个都可以，看你喜欢，完全代替 MySQLdb 的，

PyMySQL我装过，可在代码写的是`import MySQLdb`，而且装完后在`with self.__conn as c:`处执行会报错`mysql AttributeError: __enter__`，`__enter__`方法已经弃用了

**Comment by skywind3000** [comment]
那要怎么写呢？

**Comment by jiawei666** [comment]
我不会 所以我用了python2

**Comment by jiawei666** [comment]
这份数据很牛逼的，感谢作者！同时希望可以更加完善！
