### ISSUE TITLE
能否导出一个word list

### ISSUE THREAD

**Issue by amosbird** [skywind3000/ECDICT#8]
嗨，请问这个词典有办法导出一个词表吗？一行一个词。

如

```
foo
bar
baz
...
```

**Comment by skywind3000** [comment]
可以啊，解开 startdict.7z 然后用 excel 打开，速度比较慢，然后选择第一列。

**Comment by amosbird** [comment]
好吧，原来是xls格式，谢谢！

**Comment by amosbird** [comment]
![image](https://user-images.githubusercontent.com/5085485/32511059-4492f762-c3b8-11e7-8a53-29f79389309c.png)

Hmm, 还有别的办法吗

**Comment by skywind3000** [comment]
用小点的那个 ecdict.csv 70万单词量，也够你用了吧

**Comment by amosbird** [comment]
ok
