### ISSUE TITLE
Anki 制卡人福音！！！！！！正则表达式修改调用该词典产生的乱码问题

### ISSUE THREAD

**Issue by Unstoppablesss** [skywind3000/ECDICT#85]
首先Anki需要添加 Wordquery 或者 Fastquery之类的批量制卡插件
https://ankiweb.net/shared/info/775418273
https://ankiweb.net/shared/info/1807206748

导入该词典，在调用该词典生成`单词定义`的时候，会产生一些乱码
例如：正则替换前
```
`1`marital`2``2``3`['mæritәl] `4`-1`2``2`a. 丈夫的, 婚姻的, 夫妇间的 

[医] 婚姻的 
`2``4`(研托雅宝 6246/6890)
```
用anki自带的正则表达式，可以解决产生的乱码
```
1	-K=-
2	[0-9]`-=
3	``=`(多重复几次)Loop until all be replaced
4	`1`=%%
5	(`*[0-9]`*[`\-K`])=<br>
6	</br>=<br>
7	Delete the space
8	([0-9]<br>)=<br>
9	<br><br><br>=<br><br>	(多重复几次)Loop until all be replaced
10	<br>2%%<br><br>=<br><br>[%%]<br><br>
11	]%%=]
12	[a-z]*-[a-z]=
13	((.*<br><br>\[.*\]<br><br>)|%%[a-z]*<br><br>)=
14	%%=
15	[
16	]
```
替换后
```
a. 丈夫的, 婚姻的, 夫妇间的 

[医] 婚姻的 

(研托雅宝 6246/6890)
```

小心空格
`发音` 可以用tts
https://ankiweb.net/shared/info/1436550454
有高级需求的话，可以注册个Azure或者Google之类的云，调用语音转文字API ，💳：海外信用卡去某宝购买

`翻译` 简单的翻译可以使用deepl自动翻译插件
https://ankiweb.net/shared/info/972129549
使用Deepl Api key 去官网注册个号，免费版够用，💳：海外信用卡去某宝购买

其他的Anki 本地词典 addons 推荐
`English:` https://ankiweb.net/shared/info/418828045 CC-CEDICT for Anki (Chinese dictionary)
 `Japanese:`https://ankiweb.net/shared/info/13462835 MeCab UniDic Japanese Dictionary
 `Japanese:` https://ankiweb.net/shared/info/247820692 😄 KanjiEater's GoldenDict Japanese Toolbelt
 `Japanese:` https://ankiweb.net/shared/info/2055037404 Japanese Definition Scraper from weblio Dictionary

**Comment by skywind3000** [comment]
巧了，我也做过一个：

https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=20846&extra=&page=1

**Comment by Unstoppablesss** [comment]
优秀

**Comment by Unstoppablesss** [comment]
> 巧了，我直接做了一个整合版本：
> 
> https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=20846&extra=&page=1

**Comment by Unstoppablesss** [comment]
太好了
