### ISSUE TITLE
我用 ECDICT 写了一个开源的英语学习软件 Typing Learner

### ISSUE THREAD

**Issue by tangshimin** [skywind3000/ECDICT#92]
[Typing Learner](https://github.com/tangshimin/typing-learner) 可以用 MKV 视频、字幕或文档生成词库（单词本），让每个单词都有具体的语境。然后通过语境记忆单词，句子，字幕

![image](https://user-images.githubusercontent.com/16540656/185594184-f1fcbd59-ec3f-4dbc-80b1-8b746b70b29c.png)

**Comment by skywind3000** [comment]
good
