### ISSUE TITLE
添加部分动词的用法

### ISSUE THREAD

**Issue by doudou0720** [skywind3000/ECDICT#99]
如题，我希望能够在查询单词的时候得到一些语法知识
例如
输入 give
出现 give sb sth   give sth to sb 等
希望尽量优先考虑高频词，不需要所有动词都有

我想要做一个类似 **阅读 的python软件，但也希望在将其记录到生词本里时也可以查看语法来让它可以在作文中使用，您的数据库很不错，但我觉得这个部分也很有用，你也可以忽略这个issue，或者告诉我一个好一点的搭配词典

另：本人在读初二，可能没办法及时回答你，文笔疏忽也暂请谅解

**Comment by skywind3000** [comment]
你可以找剑桥高阶的字典文本数据，里面有你想要的。

**Comment by doudou0720** [comment]
好的，谢谢
